version: "3"
services:
    mysql:
        image: mysql:5.7
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - ./db_data:/var/lib/mysql
            - ./localhost.sql:/docker-entrypoint-initdb.d/install_db.sql
        environment:
            MYSQL_DATABASE: "schedule_cms"
            MYSQL_USER: "root"
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            TZ: "Asia/Tokyo"
        ports:
            - 3306:3306
    app:
        build: .
        command: sh -c "/wait-for-it.sh mysql:3306; python manage.py migrate && python manage.py runserver 0.0.0.0:3000"
        ports:
            - 3000:3000
        links:
            - mysql
        depends_on:
            - mysql
        environment:
            APP_VERSION: "local"
            DB_HOST: "mysql"
            DB_DATABASE: "schedule_cms"
            DB_USERNAME: "root"
            DB_PASSWORD: ""
        volumes:
            - .:/code:cached
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql:3306
            - PMA_USER=root
            - PMA_PASSWORD=
        depends_on:
            - mysql
        ports:
            - 8080:80
        volumes:
            - /sessions
