# Generated by Django 3.1 on 2020-11-08 08:01

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='開催日')),
                ('category', models.CharField(choices=[('u-12', 'U-12'), ('u-11', 'U-11'), ('u-10', 'U-10'), ('u-9', 'U-9'), ('u-8', 'U-8'), ('u-7', 'U-7'), ('all', 'ALL')], max_length=10, verbose_name='対象学年')),
                ('title', models.CharField(max_length=250, verbose_name='タイトル')),
                ('place', models.CharField(max_length=250, verbose_name='開催地')),
                ('content', models.TextField(blank=True, max_length=800, null=True, verbose_name='内容')),
                ('url', models.URLField(blank=True, null=True, verbose_name='参考URL')),
                ('attach', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'pdf'])], verbose_name='添付ファイル')),
                ('sort_number', models.IntegerField(blank=True, default=0, help_text='同日付内での表示順。数値の低い順から表示される。', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='表示順序')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日')),
            ],
            options={
                'verbose_name_plural': 'スケジュール',
            },
        ),
    ]
